export const dataTypes = [
  { value: "smallint", label: "SMALLINT" },
  { value: "integer", label: "INTEGER" },
  { value: "bigint", label: "BIGINT" },
  { value: "decimal", label: "DECIMAL" },
  { value: "numeric", label: "NUMERIC" },
  { value: "real", label: "REAL" },
  { value: "double precision", label: "DOUBLE PRECISION" },
  { value: "smallserial", label: "SMALLSERIAL" },
  { value: "serial", label: "SERIAL" },
  { value: "bigserial", label: "BIGSERIAL" },
  { value: "char", label: "CHAR" },
  { value: "varchar", label: "VARCHAR" },
  { value: "text", label: "TEXT" },
  { value: "boolean", label: "BOOLEAN" },
  { value: "date", label: "DATE" },
  { value: "time", label: "TIME" },
  { value: "time with time zone", label: "TIME WITH TIME ZONE" },
  { value: "timestamp", label: "TIMESTAMP" },
  { value: "timestamp with time zone", label: "TIMESTAMP WITH TIME ZONE" },
  { value: "json", label: "JSON" },
  { value: "jsonb", label: "JSONB" },
  { value: "uuid", label: "UUID" },
  { value: "xml", label: "XML" },
  { value: "money", label: "MONEY" },
  { value: "bit", label: "BIT" },
  { value: "bit varying", label: "BIT VARYING" },
  { value: "tsvector", label: "TSVECTOR" },
  { value: "tsquery", label: "TSQUERY" },
  { value: "inet", label: "INET" },
  { value: "cidr", label: "CIDR" },
  { value: "macaddr", label: "MACADDR" },
];

export const constraints = [
  { value: "none", label: "NONE" },
  { value: "primary", label: "PRIMARY KEY" },
  { value: "unique", label: "UNIQUE" },
  { value: "index", label: "INDEX" },
  { value: "foreign", label: "FOREIGN KEY" },
  { value: "check", label: "CHECK" },
  { value: "default", label: "DEFAULT" },
  { value: "not_null", label: "NOT NULL" },
  { value: "exclude", label: "EXCLUDE" },
];
